### ISSUE TITLE
(Suggestion) extension to G(IMAFD)-spec?

### ISSUE THREAD

**Issue by vskid** [cnlohr/mini-rv32ima#16]
I'm interested in seeing just how small can we make an emulator with the floating point extensions

**Comment by cnlohr** [comment]
I had considered adding the floating point extensions, but they require separate registers.  It would complicate the header file to do so.  It would be possible to make a separate folder for this, as to keep the base version simple.  You can do this.  For my current needs, no F/D is needed. But, the original mini-rv32ima base should remain as-is.

**Comment by cnlohr** [comment]
I.e. if you make a PR with a parallel folder for mini-rv32g I would certainly consider accepting it!

**Comment by misterjdrg** [comment]
And implementation of fpu flags and exact semantics of F and D is major pain in the butt

**Comment by cnlohr** [comment]
If someone submits a PR it's gonna happen, otherwise...
