### ISSUE TITLE
I Made it! esp32c3 can run linux with this wonderful emulator

### ISSUE THREAD

**Issue by xhackerustc** [cnlohr/mini-rv32ima#30]
Hi cnlohr,

I achieved your goal: "Imagine if we could run Linux on the $1 ESP32-C3"

https://github.com/xhackerustc/uc-rv32ima

And thank you again for this wonderful project

**Comment by cnlohr** [comment]
I am super curious - your video isn't playable! I want to see it.

Side-note:  Why do you need the emulator?  With PSRAM, the C3 should be capable of booting it outright, no?

**Comment by cnlohr** [comment]
I am still very excite to see the video.

**Comment by xhackerustc** [comment]
Hi,

Glad to know you are interested in it. The reason I still need the emulator is C3 can't execute code from PSRAM as S2/S3 does.

PS: I updated the video. 

Thanks

**Comment by cnlohr** [comment]
OH NO!!! I didn't know that.  That is suuuuch a bummer.  :( I Wonder if the C6 has hope.

Should I close the issue now?

**Comment by xhackerustc** [comment]
hmm,  I think it's better if I said like this: "The reason I still need the emulator is I can't make ESP32C3 directly execute code from PSRAM as S2/S3 does", may someone, especially Espressif knows the details, I will ask a query in esp-idf github proj home.

Sure you can close the issue now. Thank you again for your great project.

**Comment by cnlohr** [comment]
This is still very cool.  And congrats on getting the HackADay mention!

**Comment by raspiduino** [comment]
This motivate me to continue debugging my port of mini-rv32ima on Arduino. Thanks man. Really cool

**Comment by ElectroBoy404NotFound** [comment]
@raspiduino Hey, it's cool that you are doing it on an arduino! Mind sharing the code?

**Comment by raspiduino** [comment]
> @raspiduino Hey, it's cool that you are doing it on an arduino! Mind sharing the code?

Yes https://github.com/raspiduino/arv32-opt

**Comment by ElectroBoy404NotFound** [comment]
> > @raspiduino Hey, it's cool that you are doing it on an arduino! Mind sharing the code?
> 
> Yes https://github.com/raspiduino/arv32-opt

Wow... Finally. After months :face_palm:
