### ISSUE TITLE
U-BOOT

### ISSUE THREAD

**Issue by ElectroBoy404NotFound** [cnlohr/mini-rv32ima#34]
Hello,
How to compile U-BOOT for this?
I'm trying to run this on an ESP-32 and it needs uboot.

**Comment by cnlohr** [comment]
I don't know if anyone has compiled U-BOOT for this.  You "should" be able to just compile it for an IMA target architecutre

**Comment by ElectroBoy404NotFound** [comment]
OK I'm going to try

**Comment by upsampled** [comment]
@ElectroBoy404NotFound  how'd that turn out?

**Comment by ElectroBoy404NotFound** [comment]
> @ElectroBoy404NotFound how'd that turn out?

Saddly, I was unable to get it to compile

**Comment by ElectroBoy404NotFound** [comment]
I guess that is because I tried compiling in a github codespace, but idk
