### ISSUE TITLE
Invalid Discord Invite

### ISSUE THREAD

**Issue by ThatOneRVCoder** [cnlohr/mini-rv32ima#41]
Hi,

It looks like your discord server invite has expired. I'm working on disk i/o for mini-rv32ima and really need help.

**Comment by ThatOneRVCoder** [comment]
Also my id is `protoncat_rv`

**Comment by cnlohr** [comment]
We had to disable public invites for a bit. I will DM you.  Someone is already working on Disk I/O, I can try to connect you.

**Comment by ThatOneRVCoder** [comment]
> We had to disable public invites for a bit. I will DM you. Someone is already working on Disk I/O, I can try to connect you.

I got your DM.
