### ISSUE TITLE
Integrating Kernel on FPGA

### ISSUE THREAD

**Issue by AhmedAmrAbdellatif** [cnlohr/mini-rv32ima#42]
Hello everyone,
I'm working on a graduation project to design RISCV, We've designed RV64IMAC_Zicsr and supported M and S modes, exceptions and interrupts handling, interfaced with UART.

I want to ask if can boot your kernel on my design and generate a bitstream so i can validate my design?

**Comment by ThatOneRVCoder** [comment]
Send the src

**Comment by cnlohr** [comment]
You can get prebuilt kernels from here: https://github.com/cnlohr/mini-rv32ima-images

**Comment by ThatOneRVCoder** [comment]
> You can get prebuilt kernels from here: https://github.com/cnlohr/mini-rv32ima-images

It won't fucking work. The images are 32 bit. He built 64bit,
