### ISSUE TITLE
out of ram for doom?

### ISSUE THREAD

**Issue by neozeed** [cnlohr/mini-rv32ima#6]
I tried to run the doom thing as the video looked like fun.  but no matter what it always crashes saying its out of ram.. even allocating 2GB didnt help

./mini-rv32ima -f ../buildroot/output/images/Image -m 0x80000000

`Jan  1 00:00:01 login[28]: root login on 'console'
~ # ./emdoom [    3.336385] ------------[ cut here ]------------
[    3.336508] WARNING: CPU: 0 PID: 29 at mm/page_alloc.c:5406 0x80076c24
[    3.336638] CPU: 0 PID: 29 Comm: emdoom Not tainted 5.19.0 #6
[    3.336750] Hardware name: (efault) (DT)
[    3.336858] epc : 0x80076c24
[    3.336942]  ra : 0x80076bf8
[    3.337010] epc : 80076c24 ra : 80076bf8 sp : 806a7cc0
[    3.337117]  gp : 80923cd0 tp : 805a7000 t0 : 806a7ce8
[    3.337219]  t1 : fffff000 t2 : 00000037 s0 : 806a7d50
[    3.337313]  s1 : 00000cc0 a0 : 806a7cd0 a1 : 00000000
[    3.337399]  a2 : 00000000 a3 : 806a7ce8 a4 : 00000001
[    3.337492]  a5 : 8091f321 a6 : 806a7e00 a7 : 806a7e04
[    3.337599]  s2 : 0000000b s3 : 805a67d0 s4 : 00000000
[    3.337687]  s5 : 0000064b s6 : 00000000 s7 : 00000002
[    3.337796]  s8 : 0064b000 s9 : 00000003 s10: 00000001
[    3.337902]  s11: 806a2008 t3 : 00000004 t4 : 00000003
[    3.338008]  t5 : 00000001 t6 : 00000800
[    3.338079] status: 00001880 badaddr: 80076c24 cause: 00000003
[    3.338199] [<800776f0>] 0x800776f0
[    3.338297] [<80077c48>] 0x80077c48
[    3.338384] [<80072868>] 0x80072868
[    3.338473] [<80069c84>] 0x80069c84
[    3.338564] [<80069d0c>] 0x80069d0c
[    3.338647] [<800c0898>] 0x800c0898
[    3.338743] [<80085538>] 0x80085538
[    3.338838] [<80085a30>] 0x80085a30
[    3.338931] [<80086788>] 0x80086788
[    3.339035] [<80002048>] 0x80002048
[    3.339125] ---[ end trace 0000000000000000 ]---
[    3.339218] nommu: Allocation of length 6598656 from process 29 (emdoom) failed
[    3.339362] active_anon:0 inactive_anon:0 isolated_anon:0
[    3.339362]  active_file:0 inactive_file:0 isolated_file:0
[    3.339362]  unevictable:1980 dirty:0 writeback:0
[    3.339362]  slab_reclaimable:0 slab_unreclaimable:172
[    3.339362]  mapped:0 shmem:0 pagetables:0 bounce:0
[    3.339362]  kernel_misc_reclaimable:0
[    3.339362]  free:516712 free_pcp:0 free_cma:0
[    3.339852] Node 0 active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:7920kB isolated(anon):0kB isolated(file):0kB mapped:0kB dirty:0kB writeback:0kB shmem:0kB writeback_tmp:0kB kernel_stack:128kB pagetables:0kB all_unreclaimable? no
[    3.340191] Normal free:2066848kB boost:0kB min:5752kB low:7820kB high:9888kB reserved_highatomic:0KB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:7920kB writepending:0kB present:2097148kB managed:2076976kB mlocked:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
[    3.340580] lowmem_reserve[]: 0 0
[    3.340705] Normal: 4*4kB (M) 2*8kB (M) 4*16kB (UM) 6*32kB (U) 8*64kB (UM) 7*128kB (UM) 9*256kB (UM) 7*512kB (UM) 1*1024kB (U) 3*2048kB (M) 501*4096kB (M) = 2066848kB
[    3.341335] 1981 total pagecache pages
[    3.341426] binfmt_flat: Unable to allocate RAM for process text/data, errno -12

Segmentation fault`

thanks

**Comment by cnlohr** [comment]
Yes.  This is currently an issue.  I forgot to document it, but after building once, you have to re-build with `MAX_ORDER` = 12 or higher in `include/linux/mmzone.h`

Do you know if there's any way of setting Kernel CFLAGS in the kernel config or buildroot config?  It can be overridden with CFLAGS.

**Comment by cnlohr** [comment]
Maybe I should just regenerate the kernel with this and set it as the default kernel option on the images github.

**Comment by neozeed** [comment]
> Maybe I should just regenerate the kernel with this and set it as the default kernel option on the images github.

probably the best IMHO..   Once people know they can run things, they'll want to run things.. :D

**Comment by neozeed** [comment]
FYI I changed it in this file:  ./buildroot/output/build/linux-5.19/include/linux/mmzone.h

from 11 to 14.. for the heck of it, and yeah 
![RISCV emdoom running](https://user-images.githubusercontent.com/9031439/205734629-23d5bf8d-587f-48bf-aa96-9f215947d010.png)

**Comment by cnlohr** [comment]
I've updated notes and uploaded an image to facilitate this.
